### ISSUE TITLE
Move to CircleCI

### ISSUE THREAD

**Issue by Saphyel** [comicrelief/behat-tools#47]
I think there is no need to use concourse CI here.. shall we move to circle CI so is easier to maintain and people will have access to the build result ?

@comicrelief/qa @comicrelief/frost - Blue

**Comment by NoelLH** [comment]
@Saphyel What are the specific advantages? We could try it out I'm not particularly keen on the idea of running 2 CI tools, or porting over dozens of existing configs.

**Comment by Saphyel** [comment]
@NoelLH I'm talking about this repo only... The others has different business requirements.

As far know here we only _fire_ the tests in a container... and return the result, why to keep it in the concourseCI?

**Comment by NoelLH** [comment]
@Saphyel Why do we need a whole new tool for this project? It's _more_ things to maintain. Yes, Concourse, Travis and Circle can all run stuff but that's not a reason to use all 3 simultaneously.

Concourse pipelines can be public.

What makes you think it is easier or less config?

**Comment by Saphyel** [comment]
That's simple: ConcourseCI is more about build a pipeline where you define EVERYTHING
with Circle or travis you don't need to because they are more focused in integration.
Any issue updating concourseCI is gonna affect this project, when travis or circle we don't have that issue.

There is no advantage of using an over engineering tool like concourse CI but using travis or Circle make more sense in a small project like this.

**Comment by NoelLH** [comment]
What is the actual issue you have using Concourse? These tools are all configured with YAML files right? The fact that we have 'more stuff' on Concourse should not be a reason to start using additional tools.

I've not seen a reason Circle is actually better than Concourse for this. My reason for sticking with it is that we already use it.

I've also not seen any reason you think Circle would work better than Travis, which we also use in some places.

**Comment by Saphyel** [comment]
I think we can close this one.
