### ISSUE TITLE
RuntimeException incorrect path causes FatalThrowableError

### ISSUE THREAD

**Issue by lebaz20** [comicrelief/behat-tools#56]
`Behat\Testwork\Call\Exception\FatalThrowableError: Fatal error: Class 'Comicrelief\Behat\Context\RuntimeException' not found in vendor/comicrelief/behat-tools/src/Context/RawContext.php:133`

We need to use `\RuntimeException` instead of `RuntimeException`
https://github.com/comicrelief/behat-tools/blob/master/src/Context/RawContext.php#L133

I don't have enough permissions to create a new branch for this

**Comment by NoelLH** [comment]
Looks like this has been fixed on master
